export const TOPICS = [
{code:"1.1",theme:1,title:"Population dynamics",
 outcomes:["Describe and give reasons for the rapid increase in world population","Explain over-population and under-population","Understand the main causes of a change in population size","Give reasons for contrasting rates of natural population change","Describe and evaluate population policies"],
 guidance:["Causes and consequences of over- and under-population","How birth rate, death rate and migration make a population grow or decline","Social, economic and other factors — including government policy and HIV/AIDS — on birth and death rates"],
 cases:[{t:"A country which is over-populated",src:"India"},{t:"A country which is under-populated",src:"Australia"},{t:"A country with a high rate of natural population growth",src:"Uganda"},{t:"A country with a low rate of growth or decline",src:"Japan"}],
 mentee:{do:["Sort every factor into political, social, economic, demographic — that structure is worth marks on its own.","Always run the chain: factor → what it changes → effect on birth or death rate → effect on population.","Learn the five DTM stages with one named country each, and what causes each transition.","For policies, know the aim, two measures and one unintended consequence."],
   q:[["Explain why birth rates are falling in many more economically developed countries.",5],["Describe the consequences of over-population for a country.",4],["Using a named example, evaluate a population policy.",7]]},
 mentor:{open:"Ask them to sketch the DTM from memory and label two real countries onto it. Whatever they can't place is the session.",
   check:["They separate natural increase from total population change (migration is the difference).","They can explain <em>why</em> death rate falls before birth rate, not just that it does.","Their policy example has figures — birth rate before and after."],
   slip:"Listing factors as bare nouns (\"education\", \"religion\") with no mechanism. Push for the sentence after the noun."}},

{code:"1.2",theme:1,title:"Migration",
 outcomes:["Explain and give reasons for population migration","Demonstrate an understanding of the impacts of migration"],
 guidance:["Internal movements such as rural-urban migration, and international migration, both voluntary and involuntary","Positive and negative impacts on the destination, on the origin, and on the migrants themselves"],
 cases:[{t:"An international migration",src:"Mexico → USA"}],
 mentee:{do:["Keep push and pull factors on opposite sides of a page and make each one a full clause.","Learn impacts in a 3×2 grid: origin / destination / migrants, each with positive and negative.","Know the difference between voluntary and forced migration and one example of each.","Carry three figures for your named migration — numbers, remittances, a date."],
   q:[["Describe the difference between voluntary and forced migration.",3],["Explain the impacts of international migration on the destination country.",6],["For a named international migration, describe the reasons why people moved.",7]]},
 mentor:{open:"\"Give me your named migration in 60 seconds — from where, to where, how many, when, why.\" Time it.",
   check:["Impacts cover the source country, not just the receiving one.","They mention impacts on the migrants themselves — the most commonly forgotten third.","Push factors are pressures at origin, not attractions elsewhere."],
   slip:"Treating all migration as economic. Ask where conflict, drought and family reunification would sit."}},

{code:"1.3",theme:1,title:"Population structure",
 outcomes:["Identify and give reasons for, and implications of, different types of population structure"],
 guidance:["Age/sex pyramids of countries at different levels of economic development"],
 cases:[{t:"A country with a high dependent population",src:"Uganda / Japan"}],
 mentee:{do:["Describe a pyramid in this order: base, sides, apex, then any dents or bulges — and quote figures off the axis.","Link shape to DTM stage and to a level of development every time.","Know both kinds of dependency — youthful and ageing — and the different problems each creates.","Practise reading percentages for named age bands rather than saying \"lots\"."],
   q:[["Describe the shape of the population pyramid shown.",4],["Explain the problems caused by a high proportion of young dependants.",5],["Suggest reasons for the differences between the two pyramids.",6]]},
 mentor:{open:"Show any two pyramids side by side with the labels covered. Ask which country is more developed and how they know.",
   check:["They use data from the axis, not adjectives.","They can explain a notch or bulge (war, baby boom, policy) rather than ignoring it.","They separate <em>describe</em> from <em>explain</em> when the question splits them."],
   slip:"Saying \"more men than women\" without a figure, or describing the pyramid top-down and running out of time."}},

{code:"1.4",theme:1,title:"Population density and distribution",
 outcomes:["Describe the factors influencing the density and distribution of population"],
 guidance:["Physical, economic, social and political factors"],
 cases:[{t:"A densely populated country or area",src:"Australia (Sydney)"},{t:"A sparsely populated country or area",src:"Australia (Outback)"}],
 mentee:{do:["Do not confuse the two words: density is people per km², distribution is where they are.","Build a factor table with physical (relief, climate, soil, water, resources) against human (jobs, transport, services, government).","Learn one dense and one sparse area with real densities — a figure per km² each.","On a distribution map, describe the overall pattern first, then name two anomalies."],
   q:[["Define the term population density.",2],["Describe the distribution of population shown on the map.",4],["Explain why some areas of the world are sparsely populated.",6]]},
 mentor:{open:"\"Where would you not want to live, and why?\" Turn their answers into physical and human factors on the board.",
   check:["The definition of density includes the unit of area.","They can give a sparse example with a reason — this is the syllabus case study most often missing.","They read distribution maps as patterns (coastal, along rivers, clustered) rather than lists of places."],
   slip:"The sparsely populated example is the one pairs most often skip. Set it as homework and log it here."}},

{code:"1.5",theme:1,title:"Settlements and service provision",
 outcomes:["Explain the patterns of settlement","Describe and explain the factors influencing the sites, growth and functions of settlements","Give reasons for the hierarchy of settlements and services"],
 guidance:["Dispersed, linear and nucleated patterns","Physical factors including relief, soil and water supply; other factors including accessibility and resources","High-, middle- and low-order settlements and services; sphere of influence and threshold population"],
 cases:[{t:"Settlement and service provision in an urban area",src:"Singapore"},{t:"Settlement and service provision in a rural area",src:"Vietnam"}],
 mentee:{do:["Keep site (the land it's built on) and situation (its position relative to other places) firmly apart.","Learn the hierarchy both ways: as population rises, number of settlements falls and services get higher order.","Define range, threshold population and sphere of influence in one sentence each.","Practise identifying dispersed, linear and nucleated patterns from an OS extract."],
   q:[["Define the term sphere of influence.",2],["Describe the site and situation of the settlement shown.",4],["Explain why high-order services are found in fewer settlements.",5]]},
 mentor:{open:"Ask where they'd buy milk versus where they'd buy a laptop, then build the low-order/high-order distinction from their answer.",
   check:["Site versus situation — test with a map extract, not a definition.","They can explain threshold, not just define it.","They link wet point and dry point sites to relief and water supply."],
   slip:"Confusing range with sphere of influence. Range is how far a person will travel; sphere of influence is the area served."}},

{code:"1.6",theme:1,title:"Urban settlements",
 outcomes:["Describe and give reasons for the characteristics of, and changes in, land use in urban areas","Explain the problems of urban areas, their causes and possible solutions"],
 guidance:["Land use zones including the CBD, residential, industrial and the rural-urban fringe, in countries at different levels of development","Effects of land use change and rapid urban growth, including urban sprawl","Pollution (air, noise, water, visual), inequality, housing, traffic congestion, conflict over land use"],
 cases:[{t:"An urban area or urban areas",src:"Singapore"},{t:"Urban sprawl in a city",src:"Sydney"}],
 mentee:{do:["Learn Burgess and Hoyt as sketches you can draw in 30 seconds, with what each zone is and why.","Tie land use to bid rent: the CBD is expensive because it is most accessible.","For every urban problem, carry a cause, an effect and a named solution — the question almost always wants all three.","Use your city's real schemes and figures, not generic \"build more housing\"."],
   q:[["Describe the characteristics of the CBD of a named city.",4],["Explain why traffic congestion occurs in urban areas.",5],["For a named urban area, describe attempts to reduce one urban problem and evaluate how successful they have been.",7]]},
 mentor:{open:"Have them draw Burgess and Hoyt side by side and say what Hoyt added and why.",
   check:["They can explain <em>why</em> land use is zoned (bid rent, accessibility), not just name the zones.","Solutions are named and specific.","They can say where a model does not fit their real city — that's the AO3 mark."],
   slip:"Describing a model as if it were a real city. Models are a starting point; the marks are in the mismatch."}},

{code:"1.7",theme:1,title:"Urbanisation",
 outcomes:["Identify and suggest reasons for rapid urban growth","Describe the impacts of urban growth on rural and urban areas, and possible solutions"],
 guidance:["Physical, economic and social factors causing rural depopulation and movement to major cities","Effects of urbanisation on people and the natural environment","Characteristics of squatter settlements","Strategies to reduce the negative impacts"],
 cases:[{t:"A rapidly growing urban area in a developing country and migration to it",src:"Dharavi, Mumbai"}],
 mentee:{do:["Separate urbanisation (the proportion living in cities) from urban growth (the number of people).","Learn squatter settlement characteristics as a list you can produce fast: services, materials, density, tenure, work.","Note the effects back in the rural source area — an easy mark most candidates skip.","Know two upgrading strategies for your named city and one limitation of each."],
   q:[["Describe the characteristics of a squatter settlement.",4],["Suggest reasons for rapid urban growth in developing countries.",5],["For a named city in a developing country, describe the problems caused by rapid growth and explain attempts to solve them.",7]]},
 mentor:{open:"\"Why does someone leave a farm for a city that has no house waiting for them?\" Push until they reach both push and pull.",
   check:["They give figures for their named city's growth.","Impacts include the rural area, not only the city.","Solutions are the city's actual schemes with a named agency where possible."],
   slip:"Blurring this with 1.2. Migration is the mechanism; urbanisation is the outcome. Keep the case studies distinct."}},

{code:"2.1",theme:2,title:"Earthquakes and volcanoes",
 outcomes:["Describe the main types and features of volcanoes and earthquakes","Describe and explain their distribution","Describe the causes and effects on people and the environment","Understand that volcanoes present hazards and offer opportunities","Explain what can be done to reduce impacts"],
 guidance:["Strato-volcanoes and shield volcanoes; crater, vent, magma chamber; epicentre, focus, magnitude","Global pattern of plates, plate movement and subduction; constructive/divergent, destructive/convergent and conservative boundaries"],
 cases:[{t:"An earthquake",src:"Christchurch 2011"},{t:"A volcano",src:"Eyjafjallajökull 2010"}],
 mentee:{do:["For each boundary type, know: what moves how, whether there are earthquakes, whether there are volcanoes, and <em>why not</em> when there aren't.","Split effects into primary and secondary, and social, economic and environmental — that grid is the answer plan.","Split responses into immediate and long-term.","Learn reduction strategies as prediction, protection and preparation."],
   q:[["Describe the global distribution of earthquakes.",4],["Explain why volcanoes occur at destructive plate boundaries.",5],["For a named earthquake, describe its effects and evaluate the responses to it.",7]]},
 mentor:{open:"Give them a blank world map and ask them to draw where earthquakes happen. The Pacific ring will appear; ask why it's a ring.",
   check:["They can explain the absence of volcanoes at conservative and collision boundaries.","Haiti figures are attached to effects, not floating.","They know why people still live in hazardous areas — that's the opportunities mark."],
   slip:"Describing distribution as \"everywhere near the sea\". Insist on named plates, belts and continents."}},

{code:"2.2",theme:2,title:"Rivers",
 outcomes:["Explain the hydrological characteristics and processes in rivers and drainage basins","Understand the work of a river in eroding, transporting and depositing","Describe and explain the landforms formed","Understand that rivers present hazards and offer opportunities","Explain how the impacts of river flooding can be managed"],
 guidance:["Width, depth, speed of flow, discharge; watershed, tributary, confluence","Interception, infiltration, throughflow, groundwater flow, evaporation, overland flow","Long profile and cross-section, waterfalls, potholes, meanders, oxbow lakes, deltas, levées, flood plains","Hazards including flooding and river erosion; opportunities of living on a flood plain or delta"],
 cases:[{t:"Opportunities from a river, its hazards and their management",src:"Bangladesh flooding"}],
 mentee:{do:["Learn landform formation as a numbered sequence — examiners mark the steps, and each step is a mark.","Name the erosion processes (hydraulic action, abrasion, attrition, solution) and the transport processes (traction, saltation, suspension, solution) and use them by name.","Know how width, depth, velocity and discharge change downstream, and why velocity rises despite the gentler gradient.","Keep hard and soft engineering separate, each with an advantage and a disadvantage."],
   q:[["Describe how a waterfall is formed.",5],["Explain why flooding occurs on some rivers.",6],["For a named river, describe the flood management strategies used and evaluate their success.",7]]},
 mentor:{open:"Ask them to draw the long profile and mark where each landform belongs. Misplaced landforms show up immediately.",
   check:["Oxbow lake and meander formation are in sequence, with erosion and deposition on the correct banks.","They can state the opportunities of living on a flood plain — the case study wants both sides.","They distinguish a river's discharge from its speed."],
   slip:"\"Erosion happens\" as a step. Name which process, on which bank, and what it produces."}},

{code:"2.3",theme:2,title:"Coasts",
 outcomes:["Understand the work of the sea and wind in eroding, transporting and depositing","Describe and explain the formation of coastal landforms","Describe coral reefs and mangrove swamps and the conditions they need","Understand that coasts present hazards and offer opportunities","Explain how the impacts of coastal erosion can be managed"],
 guidance:["Cliffs, wave-cut platforms, caves, arches, stacks, stumps, bays and headlands, beaches, spits, coastal sand dunes","Hazards including coastal erosion and tropical storms"],
 cases:[{t:"Opportunities from a coastline, its hazards and their management",src:"Gold Coast, Australia"}],
 mentee:{do:["Constructive versus destructive waves: compare swash and backwash, height, frequency and what each does to a beach.","Learn longshore drift as a labelled sequence — it explains spits, and spits are asked about often.","For coral and mangroves, learn the growth conditions as numbers: temperature, depth, salinity, light.","Learn the management table by strategy, advantage, disadvantage and named example."],
   q:[["Describe the conditions needed for coral reefs to grow.",4],["Explain the formation of a spit.",5],["For a named coastline, evaluate the strategies used to manage coastal erosion.",7]]},
 mentor:{open:"\"Why is there sand at one end of the bay and not the other?\" Longshore drift usually emerges from this without prompting.",
   check:["Wave refraction is used to explain why headlands erode and bays fill.","They can name a real scheme, not just \"a sea wall\".","Coral conditions are quantified."],
   slip:"Formation answers that jump from \"crack\" to \"stack\". Insist on cave, arch, stack, stump in order with the process at each stage."}},

{code:"2.4",theme:2,title:"Weather",
 outcomes:["Describe how weather data are collected","Make calculations using information from weather instruments","Use and interpret graphs and diagrams showing weather and climate data"],
 guidance:["The characteristics, siting and use of a Stevenson Screen","Rain gauge, maximum-minimum thermometer, wet-and-dry bulb hygrometer, sunshine recorder, barometer, anemometer, wind vane, and digital equivalents; cloud type and amount"],
 cases:[],
 mentee:{do:["For each instrument: what it measures, the unit, and one siting rule with the reason.","Know the Stevenson Screen in detail — white, louvred, 1.25 m, door facing away from the sun, over grass — and why each feature exists.","Practise the calculations: mean, range, and relative humidity from wet and dry bulb readings.","Learn cloud cover in oktas and the main cloud types by height and shape."],
   q:[["Describe how rainfall is measured accurately.",4],["Explain why a Stevenson Screen is painted white and has louvred sides.",4],["Calculate the mean monthly temperature and the annual range from the table.",3]]},
 mentor:{open:"Point at anything outside and ask how they'd measure it properly. Siting errors are where the marks are.",
   check:["Every siting rule comes with a reason.","They can convert oktas and read a climate graph off two different axes.","They give units. Every time."],
   slip:"This topic is heavily assessed on Paper 2 and thinly revised. Give it a session of its own even though it looks small."}},

{code:"2.5",theme:2,title:"Climate and natural vegetation",
 outcomes:["Describe and explain the characteristics of equatorial and hot desert climates","Describe and explain tropical rainforest and hot desert ecosystems","Describe the causes and effects of deforestation of tropical rainforest"],
 guidance:["Temperature (hottest month, coolest month, annual range) and precipitation including convectional and relief rainfall","Latitude, pressure systems, winds, distance from the sea, altitude and ocean currents","The relationship between natural vegetation, soil, wildlife and climate","Effects of deforestation locally and globally, and on people"],
 cases:[{t:"An area of tropical rainforest",src:"Heart of Borneo"},{t:"An area of hot desert",src:"Mojave"}],
 mentee:{do:["Learn both climate graphs by their numbers: hottest month, coolest month, annual range, total rainfall, seasonality.","Explain the climate through the factors — latitude and low pressure for the equatorial belt, subtropical high pressure for deserts.","Learn plant and animal adaptations as feature → purpose pairs.","For deforestation, split causes from effects and effects into local, global and human."],
   q:[["Describe the characteristics of an equatorial climate.",4],["Explain how plants are adapted to survive in a hot desert.",5],["For an area of tropical rainforest, explain the causes of deforestation and describe its effects.",7]]},
 mentor:{open:"Put the two climate graphs up unlabelled. Ask which is which and what gives it away.",
   check:["They explain rainfall by convection and pressure, not just \"it's hot\".","Adaptations are paired with a purpose.","The nutrient cycle is understood — why cleared rainforest soil fails quickly."],
   slip:"Describing the rainforest layers without linking them to competition for light. The link is the explanation mark."}},

{code:"3.1",theme:3,title:"Development",
 outcomes:["Use a variety of indicators to assess a country's level of development","Identify and explain inequalities between and within countries","Classify production into sectors and give illustrations","Describe and explain how employment structure varies with development","Describe and explain globalisation and consider its impacts"],
 guidance:["GNP per capita, literacy, life expectancy and composite indices such as HDI","Primary, secondary, tertiary and quaternary sectors","Technology and transnational corporations in globalisation; impacts at local, national and global scale"],
 cases:[{t:"A transnational corporation and its global links",src:"Nike in Vietnam"}],
 mentee:{do:["For each indicator, be ready with one strength and one weakness — GDP per capita hides inequality, and so on.","Know why composite indices like HDI are preferred, and which three components they combine.","Read triangular graphs correctly: practise until you can plot and read a point in under a minute.","For your TNC, know its benefits and costs for the host country separately."],
   q:[["Explain why GNP per capita alone is not a good measure of development.",4],["Describe how employment structure changes as a country develops.",5],["For a named transnational corporation, evaluate its impacts on the host country.",7]]},
 mentor:{open:"Ask them to rank four countries with only GDP per capita, then reveal life expectancy and literacy. The ranking usually shifts — that's the lesson.",
   check:["Triangular graph reading — set two points and check.","They can give a within-country inequality example, not just between countries.","TNC impacts include the negatives: wages, conditions, profit repatriation."],
   slip:"Sector definitions given without examples. Ask for two examples each, including quaternary."}},

{code:"3.2",theme:3,title:"Food production",
 outcomes:["Describe and explain the main features of an agricultural system: inputs, processes and outputs","Recognise the causes and effects of food shortages and describe possible solutions"],
 guidance:["Commercial and subsistence; arable, pastoral and mixed; intensive and extensive","Natural inputs (relief, climate, soil) and human inputs (economic and social) and their influence on scale, organisation and products","Natural causes (drought, floods, tropical storms, pests) and economic and political causes (low investment, poor distribution, war)","Effects of food shortages, food aid, and measures to increase output"],
 cases:[{t:"A farm or agricultural system",src:"Hill sheep farming, Lake District"},{t:"A country or region suffering from food shortages",src:"South Sudan"}],
 mentee:{do:["Draw your named farm as a systems diagram: inputs, processes, outputs — and use its real figures.","Keep the farming type pairs apart: commercial/subsistence, arable/pastoral, intensive/extensive.","Split food shortage causes into physical and human before you write.","Know the solutions — irrigation, HYVs, mechanisation, aid — with a drawback each."],
   q:[["Describe the inputs of a named farming system.",4],["Explain the physical causes of food shortages.",5],["For a named country or region, describe the effects of food shortages and evaluate attempts to increase food supply.",7]]},
 mentor:{open:"\"Turn your farm into a flow diagram in two minutes.\" What they leave out of processes is what they don't understand.",
   check:["Inputs are split into physical and human.","They don't confuse processes with outputs.","The food shortage case study has dates, numbers of people affected, and named agencies."],
   slip:"Answering \"food shortage\" only as drought. Conflict and distribution failure carry equal weight in this syllabus."}},

{code:"3.3",theme:3,title:"Industry",
 outcomes:["Understand an industrial system: inputs, processes and outputs including waste","Describe and explain the factors influencing the distribution and location of factories and industrial zones"],
 guidance:["Manufacturing, processing, assembly and high technology industry","Land, labour, raw materials, fuel and power, transport, markets and political factors","Industrial zones and factories with respect to locational and siting factors"],
 cases:[{t:"An industrial zone or factory",src:"Bangalore, India"}],
 mentee:{do:["Use the same systems structure as farming: inputs, processes, outputs — and remember waste is an output.","Separate <em>location</em> (which region or country) from <em>site</em> (which exact plot, and why there).","Learn why high-technology industry locates differently: skilled labour, universities, airports, environment.","For your factory, be able to give three specific location factors with evidence."],
   q:[["Describe the inputs and outputs of a named industry.",4],["Explain the factors that influence the location of high technology industry.",5],["For a named industrial zone, explain why it developed in that location.",7]]},
 mentor:{open:"\"Why does Nike make shoes there rather than here?\" Let them build the factor list themselves, then name each factor formally.",
   check:["Waste is listed as an output.","They can distinguish site from situation factors for industry.","Political factors — tax, tariffs, regulation — appear, not just cheap labour."],
   slip:"One-word factors. \"Labour\" is not a mark; \"a large supply of low-cost semi-skilled labour\" is."}},

{code:"3.4",theme:3,title:"Tourism",
 outcomes:["Describe and explain the growth of tourism in relation to physical and human attractions","Evaluate the benefits and disadvantages of tourism to receiving areas","Understand that tourism must be carefully managed to be sustainable"],
 guidance:[],
 cases:[{t:"An area where tourism is important",src:"Gold Coast, Australia"}],
 mentee:{do:["Split attractions into physical and human, and reasons for growth into transport, income, marketing, holidays and package travel.","Group impacts as economic, social and environmental, each with positives and negatives.","Learn multiplier effect and leakage — both are worth marks in evaluation answers.","Know what makes tourism sustainable and one real scheme that does it."],
   q:[["Suggest reasons for the growth of international tourism.",5],["Describe the disadvantages of tourism for a receiving area.",4],["For a named area, evaluate attempts to make tourism more sustainable.",7]]},
 mentor:{open:"Ask what their named area would lose if tourists stopped coming tomorrow — and what it would gain.",
   check:["Both sides of every impact appear.","They can define sustainable tourism rather than just praising it.","Figures for visitor numbers and tourism income are attached to the case study."],
   slip:"Confusing ecotourism with any outdoor tourism. Ecotourism is small-scale, low-impact and returns money locally."}},

{code:"3.5",theme:3,title:"Energy",
 outcomes:["Describe the importance of non-renewable fossil fuels, renewable energy, nuclear power and fuelwood, globally and in countries at different levels of development","Evaluate the benefits and disadvantages of nuclear power and renewable energy"],
 guidance:["Coal, oil and natural gas","Geothermal, wind, HEP, wave and tidal, solar and biofuels"],
 cases:[{t:"Energy supply in a country or area",src:"Singapore"}],
 mentee:{do:["Build one table: each source with two advantages, two disadvantages and where it's used.","Explain <em>why</em> energy mix differs with development — cost, technology, resources, politics.","Nuclear needs a balanced answer: reliability and low carbon against waste, cost and accident risk.","Know why your named country's mix is what it is — its geography usually explains it."],
   q:[["Describe the advantages of using renewable energy.",4],["Explain why energy consumption varies between countries at different levels of development.",5],["Evaluate the benefits and disadvantages of nuclear power.",7]]},
 mentor:{open:"\"Why can't Singapore run on hydroelectric power?\" Physical constraints on energy choice land quickly through this.",
   check:["They distinguish energy production from energy consumption.","Renewables get honest disadvantages — intermittency, land use, cost.","Fuelwood appears — it's in the syllabus and almost always forgotten."],
   slip:"Treating \"renewable\" and \"clean\" as identical. Ask about HEP dams and biofuel land use."}},

{code:"3.6",theme:3,title:"Water",
 outcomes:["Describe methods of water supply and the proportions used for agriculture, domestic and industrial purposes at different levels of development","Explain why water shortages occur and demonstrate that careful management is needed"],
 guidance:["Reservoirs and dams, wells and bore holes, desalination","The impact of lack of clean water on people and on the potential for economic development"],
 cases:[{t:"Water supply in a country or area",src:"Singapore"}],
 mentee:{do:["Know the global split of water use — agriculture dominates — and how it shifts with development.","Separate physical water scarcity from economic water scarcity, with an example of each.","For each supply method, give one advantage and one disadvantage.","Link dirty water to specific diseases and to lost school and work days, not just \"illness\"."],
   q:[["Describe the methods used to supply water in a named country.",4],["Explain the difference between physical and economic water scarcity.",4],["Explain the impacts of a lack of clean water on people and on development.",6]]},
 mentor:{open:"Ask where their own tap water comes from, step by step. Most can't get past \"the tap\" — that's the entry point.",
   check:["Physical versus economic scarcity is clear with examples.","They mention agriculture as the largest user.","Impacts are specific: named diseases, lost income, time collecting water."],
   slip:"Answering water shortage as only rainfall. Population growth, pollution and infrastructure are equally examinable."}},

{code:"3.7",theme:3,title:"Environmental risks of economic development",
 outcomes:["Describe how economic activities threaten the natural environment and people, locally and globally","Demonstrate the need for sustainable development and management","Understand the importance of resource conservation"],
 guidance:["Soil erosion, desertification, enhanced global warming, and pollution of water, air, noise and visual"],
 cases:[{t:"An area where economic development is putting the environment at risk",src:"Nike factories, Vietnam"}],
 mentee:{do:["Learn the mechanism of the enhanced greenhouse effect, not just its name.","For soil erosion and desertification: causes, effects, and prevention strategies as three separate lists.","Sort pollution by type — water, air, noise, visual — and give a source and an effect for each.","Define sustainable development properly and apply it to a real scheme."],
   q:[["Describe the causes of soil erosion.",4],["Explain how economic development can damage the natural environment.",6],["For a named area, describe the environmental damage caused by economic activity and evaluate attempts to manage it.",7]]},
 mentor:{open:"\"Name the last thing you bought. Where did its damage go?\" It reliably reaches global links.",
   check:["The greenhouse mechanism is explained in steps.","They can define sustainable development in their own words.","The case study includes management attempts and how well they worked."],
   slip:"This topic collects marks from every other one. Ask them to link it back to industry, farming, tourism and energy."}}
];
